// Generated by CoffeeScript 1.10.0
(function() {
    var debug,
        bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

    debug = require('debug')('gitlab:BaseModel');

    module.exports = (function() {
        function exports(client) {
            this.client = client;
            this._init = bind(this._init, this);
            this.load = bind(this.load, this);
            this._init();
        }

        exports.prototype.load = function(model) {
            switch (model) {
                case "Groups":
                    return require("./Models/Groups")(this.client);
                case "Issues":
                    return require("./Models/Issues")(this.client);
                case "ProjectDeployKeys":
                    return require("./Models/ProjectDeployKeys")(this.client);
                case "ProjectHooks":
                    return require("./Models/ProjectHooks")(this.client);
                case "ProjectIssues":
                    return require("./Models/ProjectIssues")(this.client);
                case "ProjectMembers":
                    return require("./Models/ProjectMembers")(this.client);
                case "ProjectMergeRequests":
                    return require("./Models/ProjectMergeRequests")(this.client);
                case "ProjectMilestones":
                    return require("./Models/ProjectMilestones")(this.client);
                case "ProjectRepository":
                    return require("./Models/ProjectRepository")(this.client);
                case "Projects":
                    return require("./Models/Projects")(this.client);
                case "Users":
                    return require("./Models/Users")(this.client);
            }
        };

        exports.prototype._init = function() {
            this.debug = require('debug')("gitlab:Models:" + this.constructor.name);
            this.get = this.client.get;
            this.post = this.client.post;
            this.put = this.client.put;
            this["delete"] = this.client["delete"];
            if (this.init != null) {
                return this.init();
            }
        };

        return exports;

    })();

}).call(this);

//# sourceMappingURL=BaseModel.js.map
